server:
  port: 19090
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ENC(S26VUNMwMQGrekf6b2QILhs01dR7iu2BTNkPi2Q2YmlsyLop8XrRifeYQL0KpQRp)
    username: admin
    password: ENC(CY/t4Xu2Au2cNweK2LrnRQ==)
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: gpfm321@gmail.com
    password: ENC(qArboa3Sq3KTDCYxlesDJc+cOb9UbjLMYxHdsojriLo=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
global:
  url:
    admin: "http://localhost:19090"
    user: "http://localhost"
  file:
    savePath: "C:\\Users\\venh\\IdeaProjects\\uploadFiles\\admin\\"
    webPath: "/uploadFiles/admin/"
    max-size: 10 #MB
    ext: "jpg,jpeg,gif,bmp,png,zip"
  mail:
    templates:
      path: "C:\\Users\\venh\\IdeaProjects\\admin\\src\\main\\resources\\templates\\mail\\"

jasypt:
  key: ${jasypt_key}